// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/shynggys9219/ap2_microservices_project/user_svc/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// CustomerEventStorage is an autogenerated mock type for the CustomerEventStorage type
type CustomerEventStorage struct {
	mock.Mock
}

type CustomerEventStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *CustomerEventStorage) EXPECT() *CustomerEventStorage_Expecter {
	return &CustomerEventStorage_Expecter{mock: &_m.Mock}
}

// Push provides a mock function with given fields: ctx, client
func (_m *CustomerEventStorage) Push(ctx context.Context, client model.Customer) error {
	ret := _m.Called(ctx, client)

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Customer) error); ok {
		r0 = rf(ctx, client)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CustomerEventStorage_Push_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Push'
type CustomerEventStorage_Push_Call struct {
	*mock.Call
}

// Push is a helper method to define mock.On call
//   - ctx context.Context
//   - client model.Customer
func (_e *CustomerEventStorage_Expecter) Push(ctx interface{}, client interface{}) *CustomerEventStorage_Push_Call {
	return &CustomerEventStorage_Push_Call{Call: _e.mock.On("Push", ctx, client)}
}

func (_c *CustomerEventStorage_Push_Call) Run(run func(ctx context.Context, client model.Customer)) *CustomerEventStorage_Push_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Customer))
	})
	return _c
}

func (_c *CustomerEventStorage_Push_Call) Return(_a0 error) *CustomerEventStorage_Push_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CustomerEventStorage_Push_Call) RunAndReturn(run func(context.Context, model.Customer) error) *CustomerEventStorage_Push_Call {
	_c.Call.Return(run)
	return _c
}

// NewCustomerEventStorage creates a new instance of CustomerEventStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomerEventStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomerEventStorage {
	mock := &CustomerEventStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
