// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EmailTemplateRenderer is an autogenerated mock type for the EmailTemplateRenderer type
type EmailTemplateRenderer struct {
	mock.Mock
}

type EmailTemplateRenderer_Expecter struct {
	mock *mock.Mock
}

func (_m *EmailTemplateRenderer) EXPECT() *EmailTemplateRenderer_Expecter {
	return &EmailTemplateRenderer_Expecter{mock: &_m.Mock}
}

// Render provides a mock function with given fields: templateName, data
func (_m *EmailTemplateRenderer) Render(templateName string, data map[string]interface{}) (string, error) {
	ret := _m.Called(templateName, data)

	if len(ret) == 0 {
		panic("no return value specified for Render")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, map[string]interface{}) (string, error)); ok {
		return rf(templateName, data)
	}
	if rf, ok := ret.Get(0).(func(string, map[string]interface{}) string); ok {
		r0 = rf(templateName, data)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, map[string]interface{}) error); ok {
		r1 = rf(templateName, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EmailTemplateRenderer_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type EmailTemplateRenderer_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
//   - templateName string
//   - data map[string]interface{}
func (_e *EmailTemplateRenderer_Expecter) Render(templateName interface{}, data interface{}) *EmailTemplateRenderer_Render_Call {
	return &EmailTemplateRenderer_Render_Call{Call: _e.mock.On("Render", templateName, data)}
}

func (_c *EmailTemplateRenderer_Render_Call) Run(run func(templateName string, data map[string]interface{})) *EmailTemplateRenderer_Render_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(map[string]interface{}))
	})
	return _c
}

func (_c *EmailTemplateRenderer_Render_Call) Return(_a0 string, _a1 error) *EmailTemplateRenderer_Render_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EmailTemplateRenderer_Render_Call) RunAndReturn(run func(string, map[string]interface{}) (string, error)) *EmailTemplateRenderer_Render_Call {
	_c.Call.Return(run)
	return _c
}

// NewEmailTemplateRenderer creates a new instance of EmailTemplateRenderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmailTemplateRenderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmailTemplateRenderer {
	mock := &EmailTemplateRenderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
