// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/shynggys9219/ap2_microservices_project/emailer_service/internal/model"
)

// CustomerUsecase is an autogenerated mock type for the CustomerUsecase type
type CustomerUsecase struct {
	mock.Mock
}

type CustomerUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *CustomerUsecase) EXPECT() *CustomerUsecase_Expecter {
	return &CustomerUsecase_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: ctx, customer
func (_m *CustomerUsecase) Send(ctx context.Context, customer model.Customer) error {
	ret := _m.Called(ctx, customer)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Customer) error); ok {
		r0 = rf(ctx, customer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CustomerUsecase_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type CustomerUsecase_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - customer model.Customer
func (_e *CustomerUsecase_Expecter) Send(ctx interface{}, customer interface{}) *CustomerUsecase_Send_Call {
	return &CustomerUsecase_Send_Call{Call: _e.mock.On("Send", ctx, customer)}
}

func (_c *CustomerUsecase_Send_Call) Run(run func(ctx context.Context, customer model.Customer)) *CustomerUsecase_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Customer))
	})
	return _c
}

func (_c *CustomerUsecase_Send_Call) Return(_a0 error) *CustomerUsecase_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CustomerUsecase_Send_Call) RunAndReturn(run func(context.Context, model.Customer) error) *CustomerUsecase_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewCustomerUsecase creates a new instance of CustomerUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomerUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomerUsecase {
	mock := &CustomerUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
