// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// WithinTransactionFunc is an autogenerated mock type for the WithinTransactionFunc type
type WithinTransactionFunc struct {
	mock.Mock
}

type WithinTransactionFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *WithinTransactionFunc) EXPECT() *WithinTransactionFunc_Expecter {
	return &WithinTransactionFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, fn
func (_m *WithinTransactionFunc) Execute(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithinTransactionFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type WithinTransactionFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(context.Context) error
func (_e *WithinTransactionFunc_Expecter) Execute(ctx interface{}, fn interface{}) *WithinTransactionFunc_Execute_Call {
	return &WithinTransactionFunc_Execute_Call{Call: _e.mock.On("Execute", ctx, fn)}
}

func (_c *WithinTransactionFunc_Execute_Call) Run(run func(ctx context.Context, fn func(context.Context) error)) *WithinTransactionFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *WithinTransactionFunc_Execute_Call) Return(_a0 error) *WithinTransactionFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WithinTransactionFunc_Execute_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *WithinTransactionFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewWithinTransactionFunc creates a new instance of WithinTransactionFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWithinTransactionFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *WithinTransactionFunc {
	mock := &WithinTransactionFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
